id: ID814E2E0
legacy_id: P001830
ocr_import_info:
  bdrc_scan_id: W23872
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T09:57:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:52:49.977607+00:00'
last_modified: 2022-09-02 12:53:14.957027
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23872
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23872
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས།
  author: འབྲོང་རྩེ་བློ་བཟང་ཚུལ་ཁྲིམས།
statistics:
  ocr_word_mean_confidence_index: 0.8048980117166591
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I1KG1723:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1723
      total_pages: 456
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1723.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.793281049421076
    legacy_id: v001
  I1KG1724:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1724
      total_pages: 391
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG1724.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8195683274284976
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
