id: ID814E2E0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T09:59:56+00:00'
last_modified: '2022-06-07T15:18:41.062015+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23872
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    734C:
      image_group_id: I1KG1723
      title: ''
      total_pages: 456
      order: 1
      base_file: 734C.txt
    '8182':
      image_group_id: I1KG1724
      title: ''
      total_pages: 391
      order: 2
      base_file: 8182.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
